### ISSUE TITLE
[GMCM] Cuts off options in languages not English

### ISSUE THREAD

**Issue by atravita-mods** [spacechase0/StardewValleyMods#275]
![image](https://user-images.githubusercontent.com/94934860/193477790-f9f36fa9-6cd4-4a3b-b989-e02bd72b9cb8.png)

Left: game in English
Right: game in German (no translation, which is why the words are in English)

**Comment by jltaylor-us** [comment]
I think this maybe has nothing to do with language, per se, and is just triggered by the fact that the German version of SpriteFont1 is shorter than the default version (LineSpacing 33 as opposed to 50).  That perturbs the menu content layout enough that the bug becomes obvious, but it can be triggered in layouts in English, too.

I think the problem is that the math to compute the number of rows for the scrollbar is truncating rather than rounding up.  (This may have been my oversight from when I made the not-fixed-row-height PR.)  Specifically, [here](https://github.com/spacechase0/StardewValleyMods/blob/5baf8d2608943491f2d80a9ecb74543f430a3c59/SpaceShared/UI/Table.cs#L40), [here](https://github.com/spacechase0/StardewValleyMods/blob/5baf8d2608943491f2d80a9ecb74543f430a3c59/SpaceShared/UI/Table.cs#L118), and [here](https://github.com/spacechase0/StardewValleyMods/blob/5baf8d2608943491f2d80a9ecb74543f430a3c59/SpaceShared/UI/Table.cs#L201).

If that is, in fact, the problem then it can be solved by rounding up instead of truncating:
```diff
-                this.SizeImpl = new Vector2(value.X, ((int)value.Y) / this.RowHeight * this.RowHeight);
+                this.SizeImpl = new Vector2(value.X, ((int)value.Y + this.RowHeight - 1) / this.RowHeight * this.RowHeight);
```
```diff
-                this.Scrollbar.Rows = this.ContentHeight / this.RowHeight;
+                this.Scrollbar.Rows = (this.ContentHeight + this.RowHeight - 1) / this.RowHeight;
```
```diff
-            this.Scrollbar.Rows = this.ContentHeight / this.RowHeight;
+            this.Scrollbar.Rows = (this.ContentHeight + this.RowHeight - 1) / this.RowHeight;
```

(of course, it would probably be nicer to make this a helper (e.g. `PxToRows`) rather than repeating that logic three places)

**Comment by jltaylor-us** [comment]
apparently not that first one... that changes the frame size.

See #357
